# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survivor_name', models.CharField(max_length=200, verbose_name='Name')),
                ('survivor_age', models.IntegerField(verbose_name='Age')),
            ],
        ),
    ]
