# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0003_auto_20170626_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survivor',
            old_name='survivor_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='survivor',
            old_name='survivor_name',
            new_name='name',
        ),
    ]
