# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0005_auto_20170627_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='survivor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventory', serialize=False, to='survivors.Survivor'),
        ),
        migrations.AlterField(
            model_name='location',
            name='survivor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='location', serialize=False, to='survivors.Survivor'),
        ),
    ]
