# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0006_auto_20170627_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('survivor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='items', serialize=False, to='survivors.Survivor')),
                ('water', models.PositiveIntegerField(default=0)),
                ('food', models.PositiveIntegerField(default=0)),
                ('med', models.PositiveIntegerField(default=0)),
                ('ammo', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='survivor',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
