# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-27 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survivors', '0004_auto_20170626_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('survivor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='survivors.Survivor')),
                ('water', models.PositiveIntegerField(default=0)),
                ('food', models.PositiveIntegerField(default=0)),
                ('med', models.PositiveIntegerField(default=0)),
                ('ammo', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_lng',
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
